import datetime as _datetime
import os as _os
from collections.abc import Iterable as _Iterable, Iterator as _Iterator, Sequence as _Sequence
from typing import (
    IO as _IO,
    ClassVar as _ClassVar,
    Literal as _Literal,
    NoReturn as _Never,
    final as _final,
    overload as _overload,
)

from .dml.color import RGBColor as _RGBColor
from .enum.dml import (
    MSO_ARROWHEAD_LENGTH as _MSO_ARROWHEAD_LENGTH,
    MSO_ARROWHEAD_STYLE as _MSO_ARROWHEAD_STYLE,
    MSO_ARROWHEAD_WIDTH as _MSO_ARROWHEAD_WIDTH,
    MSO_COLOR_TYPE as _MSO_COLOR_TYPE,
    MSO_FILL_TYPE as _MSO_FILL_TYPE,
    MSO_LINE_DASH_STYLE as _MSO_LINE_DASH_STYLE,
    MSO_PATTERN_TYPE as _MSO_PATTERN_TYPE,
    MSO_THEME_COLOR_INDEX as _MSO_THEME_COLOR,
)
from .enum.lang import MSO_LANGUAGE_ID as _MSO_LANGUAGE_ID
from .enum.shapes import (
    MSO_CONNECTOR_TYPE as _MSO_CONNECTOR_TYPE,
    MSO_SHAPE as _MSO_SHAPE,
    MSO_SHAPE_TYPE as _MSO_SHAPE_TYPE,
    PP_PLACEHOLDER_TYPE as _PP_PLACEHOLDER,
)
from .enum.text import (
    MSO_AUTO_SIZE as _MSO_AUTO_SIZE,
    MSO_TEXT_UNDERLINE_TYPE as _MSO_UNDERLINE,
    MSO_VERTICAL_ANCHOR as _MSO_ANCHOR,
    PP_PARAGRAPH_ALIGNMENT as _PP_ALIGN,
)
from .util import Length as _Length

_Path = str | _os.PathLike[str]
_Color = _RGBColor | tuple[int, int, int] | str
_ImageFile = _Path | bytes | _IO[bytes]
_OdpDiagnostics = list[tuple[str, str]]
_AutoNumberScheme = _Literal[
    "alphaLcParenBoth", "alphaUcParenBoth", "alphaLcParenR", "alphaUcParenR",
    "alphaLcPeriod", "alphaUcPeriod", "arabicParenBoth", "arabicParenR", "arabicPeriod",
    "arabicPlain", "romanLcParenBoth", "romanUcParenBoth", "romanLcParenR", "romanUcParenR",
    "romanLcPeriod", "romanUcPeriod", "circleNumDbPlain", "circleNumWdBlackPlain",
    "circleNumWdWhitePlain", "arabicDbPeriod", "arabicDbPlain", "ea1ChsPeriod", "ea1ChsPlain",
    "ea1ChtPeriod", "ea1ChtPlain", "ea1JpnChsDbPeriod", "ea1JpnKorPlain", "ea1JpnKorPeriod",
    "arabic1Minus", "arabic2Minus", "hebrew2Minus", "thaiAlphaPeriod", "thaiAlphaParenR",
    "thaiAlphaParenBoth", "thaiNumPeriod", "thaiNumParenR", "thaiNumParenBoth",
    "hindiAlphaPeriod", "hindiNumPeriod", "hindiNumParenR", "hindiAlpha1Period",
]
__all__ = [
    "Presentation", "CommentAuthor", "Comment", "CommentReply",
    "BoundingBox", "TextLineLayout", "TextFrameLayout", "ValidationIssue",
    "CoreProperties", "Section", "MediaInfo", "GradientStops", "GradientStop",
    "SlideLayout", "SlideLayoutCollection", "Slide", "Background",
    "SlideCollection", "Shape", "ShapeCollection", "PlaceholderCollection",
    "Image", "AdjustmentCollection", "FillFormat", "LineFormat", "LineEndFormat",
    "ColorFormat", "ShadowFormat",
    "TextFrame", "Paragraph", "ParagraphCollection", "Run", "RunCollection",
    "Hyperlink", "ShapeClickAction", "ShapeHyperlink", "Font", "Table", "Column", "ColumnCollection", "Row",
    "RowCollection", "Cell",
    "PlaceholderFormat", "HeaderFooter", "SlideTransition", "SlideMaster",
    "SlideMasterCollection", "Theme", "ThemeFonts", "ThemeFontSet",
    "ThemeColors", "MasterTextStyles", "TextStyleList", "TextStyleLevel",
]
_TransitionType = _Literal[
    "fade", "push", "wipe", "split", "cover", "uncover", "cut", "zoom"
]
_TransitionDirection = _Literal[
    "left", "up", "right", "down", "left-up", "right-up", "left-down",
    "right-down", "in", "out", "horizontal-in", "horizontal-out",
    "vertical-in", "vertical-out",
]


@_final
class CommentAuthor:
    def __new__(cls, *, _private: _Never) -> CommentAuthor: ...
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def initials(self) -> str | None: ...
    @property
    def user_id(self) -> str: ...
    @property
    def provider_id(self) -> str: ...


@_final
class CommentReply:
    def __new__(cls, *, _private: _Never) -> CommentReply: ...
    @property
    def id(self) -> str: ...
    @property
    def author_id(self) -> str: ...
    @property
    def status(self) -> str | None: ...
    @property
    def created(self) -> str: ...
    @property
    def text(self) -> str: ...


@_final
class Comment:
    def __new__(cls, *, _private: _Never) -> Comment: ...
    @property
    def id(self) -> str: ...
    @property
    def author_id(self) -> str: ...
    @property
    def status(self) -> str | None: ...
    @property
    def created(self) -> str: ...
    @property
    def text(self) -> str: ...
    @property
    def replies(self) -> tuple[CommentReply, ...]: ...


@_final
class BoundingBox:
    def __new__(cls, *, _private: _Never) -> BoundingBox: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...


@_final
class TextLineLayout:
    def __new__(cls, *, _private: _Never) -> TextLineLayout: ...
    @property
    def paragraph_index(self) -> int: ...
    @property
    def text(self) -> str: ...
    @property
    def bounds(self) -> BoundingBox: ...
    @property
    def baseline(self) -> float: ...
    @property
    def font_size(self) -> float: ...


@_final
class TextFrameLayout:
    def __new__(cls, *, _private: _Never) -> TextFrameLayout: ...
    @property
    def slide_index(self) -> int: ...
    @property
    def shape_id(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def autofit(self) -> str: ...
    @property
    def frame(self) -> BoundingBox: ...
    @property
    def usable(self) -> BoundingBox: ...
    @property
    def font_scale(self) -> float: ...
    @property
    def height(self) -> float: ...
    @property
    def overflow(self) -> bool: ...
    @property
    def lines(self) -> tuple[TextLineLayout, ...]: ...


@_final
class ValidationIssue:
    def __new__(cls, *, _private: _Never) -> ValidationIssue: ...
    @property
    def kind(self) -> str: ...
    @property
    def message(self) -> str: ...


@_final
class CoreProperties:
    def __new__(cls, *, _private: _Never) -> CoreProperties: ...
    @property
    def author(self) -> str: ...
    @author.setter
    def author(self, value: str | None) -> None: ...
    @property
    def category(self) -> str: ...
    @category.setter
    def category(self, value: str | None) -> None: ...
    @property
    def comments(self) -> str: ...
    @comments.setter
    def comments(self, value: str | None) -> None: ...
    @property
    def content_status(self) -> str: ...
    @content_status.setter
    def content_status(self, value: str | None) -> None: ...
    @property
    def identifier(self) -> str: ...
    @identifier.setter
    def identifier(self, value: str | None) -> None: ...
    @property
    def keywords(self) -> str: ...
    @keywords.setter
    def keywords(self, value: str | None) -> None: ...
    @property
    def language(self) -> str: ...
    @language.setter
    def language(self, value: str | None) -> None: ...
    @property
    def last_modified_by(self) -> str: ...
    @last_modified_by.setter
    def last_modified_by(self, value: str | None) -> None: ...
    @property
    def subject(self) -> str: ...
    @subject.setter
    def subject(self, value: str | None) -> None: ...
    @property
    def title(self) -> str: ...
    @title.setter
    def title(self, value: str | None) -> None: ...
    @property
    def version(self) -> str: ...
    @version.setter
    def version(self, value: str | None) -> None: ...
    @property
    def created(self) -> _datetime.datetime | None: ...
    @created.setter
    def created(self, value: _datetime.datetime | None) -> None: ...
    @property
    def last_printed(self) -> _datetime.datetime | None: ...
    @last_printed.setter
    def last_printed(self, value: _datetime.datetime | None) -> None: ...
    @property
    def modified(self) -> _datetime.datetime | None: ...
    @modified.setter
    def modified(self, value: _datetime.datetime | None) -> None: ...
    @property
    def revision(self) -> int: ...
    @revision.setter
    def revision(self, value: int | None) -> None: ...


@_final
class Section:
    def __new__(cls, *, _private: _Never) -> Section: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __repr__(self) -> str: ...
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def slide_indices(self) -> list[int]: ...


@_final
class MediaInfo:
    def __new__(cls, *, _private: _Never) -> MediaInfo: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __repr__(self) -> str: ...
    @property
    def shape_id(self) -> int: ...
    @property
    def kind(self) -> _Literal["video", "audio"]: ...
    @property
    def content_type(self) -> str | None: ...
    @property
    def linked(self) -> bool: ...
    @property
    def target(self) -> str: ...


@_final
class Presentation:
    def __new__(cls, path: _Path | None = None) -> Presentation: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> Presentation: ...
    def save(self, path: _Path) -> None: ...
    def to_bytes(self) -> bytes: ...
    def to_pdf(
        self,
        *,
        fonts: _Sequence[tuple[str, bytes]] | None = None,
        font_dir: _Path | None = None,
    ) -> bytes:
        """Render the presentation to PDF bytes.

        ``fonts`` gives ``(family, font bytes)`` pairs and ``font_dir`` a
        directory whose ``.ttf``, ``.otf`` and ``.ttc`` files are named after
        their family. Those fonts come before the bundled fonts, as
        ``rpptx convert --font-dir`` does. A missing ``font_dir`` raises
        ``FileNotFoundError`` and a file ``NotADirectoryError``. Every render
        method and ``text_layout`` take the same two arguments, so a fit check
        measures with the fonts the render draws.
        """
    def render_slide_to_png(
        self,
        slide_index: int,
        dpi: float = 150.0,
        *,
        fonts: _Sequence[tuple[str, bytes]] | None = None,
        font_dir: _Path | None = None,
    ) -> bytes | None: ...
    def render_all_slides(
        self,
        dpi: float = 150.0,
        *,
        fonts: _Sequence[tuple[str, bytes]] | None = None,
        font_dir: _Path | None = None,
    ) -> list[bytes]: ...
    def text_layout(
        self,
        *,
        width_factor: float = 1.0,
        fonts: _Sequence[tuple[str, bytes]] | None = None,
        font_dir: _Path | None = None,
    ) -> tuple[TextFrameLayout, ...]: ...
    def to_notes_pdf(
        self,
        *,
        fonts: _Sequence[tuple[str, bytes]] | None = None,
        font_dir: _Path | None = None,
    ) -> bytes: ...
    def render_all_notes(
        self,
        dpi: float = 150.0,
        *,
        fonts: _Sequence[tuple[str, bytes]] | None = None,
        font_dir: _Path | None = None,
    ) -> list[bytes]: ...
    @_overload
    def render_slides(
        self,
        *,
        dpi: float = 150.0,
        format: _Literal["png", "jpg", "jpeg"] = "png",
        quality: int | None = None,
        transparent: bool = False,
        slides: list[int] | None = None,
    ) -> list[bytes]: ...
    @_overload
    def render_slides(
        self,
        *,
        dpi: float = 150.0,
        format: _Literal["tif", "tiff"],
        quality: int | None = None,
        transparent: bool = False,
        slides: list[int] | None = None,
    ) -> bytes: ...
    def to_pdfa(self, profile: _Literal["pdfa-2b", "pdfa-3b"] = "pdfa-2b") -> bytes: ...
    def to_handout_pdf(self, slides_per_page: _Literal[1, 2, 3, 4, 6, 9] = 6) -> bytes: ...
    def render_all_handouts(
        self, slides_per_page: _Literal[1, 2, 3, 4, 6, 9] = 6, dpi: float = 150.0
    ) -> list[bytes]: ...
    @staticmethod
    def from_odp(file: _Path | bytes) -> tuple[Presentation, _OdpDiagnostics]: ...
    def to_odp(self) -> tuple[bytes, _OdpDiagnostics]: ...
    def save_odp(self, path: _Path) -> _OdpDiagnostics: ...
    @property
    def core_properties(self) -> CoreProperties: ...
    @property
    def sections(self) -> tuple[Section, ...]: ...
    def set_sections(self, sections: list[tuple[str, list[int]]]) -> None: ...
    def try_replace_text(
        self, placeholder: str, replacement: str, *, expect: int | None = None
    ) -> int: ...
    def replace_text(
        self, placeholder: str, replacement: str, *, expect: int | None = None
    ) -> int: ...
    def validate(self) -> tuple[ValidationIssue, ...]: ...
    @property
    def slide_width(self) -> _Length | None: ...
    @slide_width.setter
    def slide_width(self, value: int) -> None: ...
    @property
    def slide_height(self) -> _Length | None: ...
    @slide_height.setter
    def slide_height(self, value: int) -> None: ...
    @property
    def comment_authors(self) -> tuple[CommentAuthor, ...]: ...
    def add_comment_author(
        self,
        *,
        id: str,
        name: str,
        user_id: str,
        provider_id: str,
        initials: str | None = None,
    ) -> None: ...
    @property
    def slide_layouts(self) -> SlideLayoutCollection: ...
    @property
    def slides(self) -> SlideCollection: ...
    # Header and footer, masters (#311).
    def set_header_footer(
        self,
        slide_number: bool = True,
        footer: str | None = None,
        date: str | None = None,
        hide_on_title: bool = True,
        date_format: str = "datetime1",
    ) -> None: ...
    def apply_theme(
        self,
        source: _Path | bytes | _IO[bytes] | Presentation,
        *,
        import_master: bool = False,
    ) -> None: ...
    @property
    def slide_masters(self) -> SlideMasterCollection: ...
    @property
    def slide_master(self) -> SlideMaster: ...


@_final
class SlideLayout:
    def __new__(cls, *, _private: _Never) -> SlideLayout: ...
    @property
    def name(self) -> str | None: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def slide_master(self) -> SlideMaster: ...
    @property
    def shapes(self) -> ShapeCollection: ...
    @property
    def placeholders(self) -> PlaceholderCollection: ...
    @property
    def background(self) -> Background: ...
    @property
    def follow_master_background(self) -> bool: ...
    @follow_master_background.setter
    def follow_master_background(self, value: bool) -> None: ...
    @property
    def show_master_shapes(self) -> bool: ...
    @show_master_shapes.setter
    def show_master_shapes(self, value: bool) -> None: ...
    @property
    def used_by_slides(self) -> tuple[Slide, ...]: ...
    def __eq__(self, other: object, /) -> bool: ...


@_final
class SlideLayoutCollection:
    def __new__(cls, *, _private: _Never) -> SlideLayoutCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> SlideLayout: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[SlideLayout]: ...
    def __iter__(self) -> _Iterator[SlideLayout]: ...
    def index(self, slide_layout: SlideLayout) -> int: ...
    def get_by_name(
        self, name: str, default: SlideLayout | None = None
    ) -> SlideLayout | None: ...
    def remove(self, slide_layout: SlideLayout) -> None: ...
    def duplicate(self, slide_layout: SlideLayout) -> SlideLayout: ...


@_final
class Slide:
    def __new__(cls, *, _private: _Never) -> Slide: ...
    def __eq__(self, other: object, /) -> bool: ...
    __hash__: _ClassVar[None]  # type: ignore[assignment]
    @property
    def shapes(self) -> ShapeCollection: ...
    @property
    def placeholders(self) -> PlaceholderCollection: ...
    @property
    def notes_text(self) -> str | None: ...
    @notes_text.setter
    def notes_text(self, value: str) -> None: ...
    def try_replace_text(
        self,
        placeholder: str,
        replacement: str,
        *,
        expect: int | None = None,
        notes: bool = True,
    ) -> int: ...
    @property
    def slide_layout(self) -> SlideLayout: ...
    @slide_layout.setter
    def slide_layout(self, value: SlideLayout) -> None: ...
    @property
    def hidden(self) -> bool: ...
    @hidden.setter
    def hidden(self, value: bool) -> None: ...
    @property
    def slide_id(self) -> int: ...
    @property
    def media(self) -> tuple[MediaInfo, ...]: ...
    def extract_media(self, shape_id: int) -> bytes | None: ...
    def replace_media(
        self, shape_id: int, media_file: _ImageFile, mime_type: str | None = None
    ) -> None: ...
    def remove_media(self, shape_id: int) -> None: ...
    @property
    def background(self) -> Background: ...
    @property
    def follow_master_background(self) -> bool: ...
    @follow_master_background.setter
    def follow_master_background(self, value: bool) -> None: ...
    @property
    def show_master_shapes(self) -> bool: ...
    @show_master_shapes.setter
    def show_master_shapes(self, value: bool) -> None: ...
    @property
    def comments(self) -> tuple[Comment, ...]: ...
    def add_comment(
        self, *, id: str, author_id: str, created: str, text: str,
        shape_id: int | None = None, text_start: int | None = None,
        text_length: int | None = None,
    ) -> None: ...
    def reply_to_comment(
        self,
        comment_id: str,
        *,
        id: str,
        author_id: str,
        created: str,
        text: str,
    ) -> None: ...
    def resolve_comment(self, comment_id: str) -> None: ...
    def remove_comment(self, comment_id: str) -> None: ...
    def move_comment(self, from_: int, to: int) -> None: ...
    def move_reply(self, comment_id: str, from_: int, to: int) -> None: ...
    # Header and footer, transition (#311).
    @property
    def header_footer(self) -> HeaderFooter: ...
    @property
    def transition(self) -> SlideTransition: ...


@_final
class SlideCollection:
    def __new__(cls, *, _private: _Never) -> SlideCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Slide: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Slide]: ...
    def __iter__(self) -> _Iterator[Slide]: ...
    def add_slide(self, layout: SlideLayout) -> Slide: ...
    def import_slide(
        self, slide: Slide, layout: SlideLayout | None = None, index: int | None = None
    ) -> Slide: ...
    def remove(self, slide: Slide) -> None: ...
    def duplicate(self, slide: Slide) -> Slide: ...
    def move(self, from_: int, to: int) -> None: ...


@_final
class Background:
    def __new__(cls, *, _private: _Never) -> Background: ...
    @property
    def fill(self) -> FillFormat: ...


@_final
class Shape:
    def __new__(cls, *, _private: _Never) -> Shape: ...
    @property
    def click_action(self) -> ShapeClickAction: ...
    @property
    def left(self) -> _Length | None: ...
    @left.setter
    def left(self, value: int) -> None: ...
    @property
    def top(self) -> _Length | None: ...
    @top.setter
    def top(self, value: int) -> None: ...
    @property
    def width(self) -> _Length | None: ...
    @width.setter
    def width(self, value: int) -> None: ...
    @property
    def height(self) -> _Length | None: ...
    @height.setter
    def height(self, value: int) -> None: ...
    def effective_geometry(self) -> tuple[_Length, _Length, _Length, _Length] | None: ...
    @property
    def shape_id(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def rotation(self) -> float: ...
    @rotation.setter
    def rotation(self, value: float) -> None: ...
    @property
    def shape_type(self) -> _MSO_SHAPE_TYPE | None: ...
    @property
    def auto_shape_type(self) -> _MSO_SHAPE | None: ...
    @auto_shape_type.setter
    def auto_shape_type(self, value: _MSO_SHAPE | str) -> None: ...
    @property
    def adjustments(self) -> AdjustmentCollection: ...
    @property
    def fill(self) -> FillFormat: ...
    @property
    def line(self) -> LineFormat: ...
    @property
    def shadow(self) -> ShadowFormat: ...
    @property
    def theme_effect_index(self) -> int | None: ...
    @theme_effect_index.setter
    def theme_effect_index(self, value: int) -> None: ...
    @property
    def xml(self) -> bytes: ...
    @property
    def image(self) -> Image: ...
    @property
    def crop_left(self) -> float: ...
    @crop_left.setter
    def crop_left(self, value: float) -> None: ...
    @property
    def crop_top(self) -> float: ...
    @crop_top.setter
    def crop_top(self, value: float) -> None: ...
    @property
    def crop_right(self) -> float: ...
    @crop_right.setter
    def crop_right(self, value: float) -> None: ...
    @property
    def crop_bottom(self) -> float: ...
    @crop_bottom.setter
    def crop_bottom(self, value: float) -> None: ...
    def replace_image(self, image_file: _ImageFile) -> None: ...
    @property
    def shapes(self) -> ShapeCollection: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def has_text_frame(self) -> bool: ...
    @property
    def text_frame(self) -> TextFrame: ...
    @property
    def has_table(self) -> bool: ...
    @property
    def table(self) -> Table: ...
    # Placeholders (#311).
    @property
    def is_placeholder(self) -> bool: ...
    @property
    def placeholder_format(self) -> PlaceholderFormat: ...

    @property
    def alt_text(self) -> str | None: ...
    @alt_text.setter
    def alt_text(self, value: str | None) -> None: ...
    @property
    def alt_title(self) -> str | None: ...
    @alt_title.setter
    def alt_title(self, value: str | None) -> None: ...
    @property
    def decorative(self) -> bool: ...
    @decorative.setter
    def decorative(self, value: bool) -> None: ...
    @property
    def flip_h(self) -> bool: ...
    @flip_h.setter
    def flip_h(self, value: bool) -> None: ...
    @property
    def flip_v(self) -> bool: ...
    @flip_v.setter
    def flip_v(self, value: bool) -> None: ...
    def ungroup(self) -> list[Shape]: ...
    def insert_picture(self, image_file: _ImageFile) -> Shape: ...
    def begin_connect(self, shape: Shape, cxn_pt_idx: int) -> None: ...
    def end_connect(self, shape: Shape, cxn_pt_idx: int) -> None: ...
    @property
    def begin_x(self) -> _Length | None: ...
    @begin_x.setter
    def begin_x(self, value: int) -> None: ...
    @property
    def begin_y(self) -> _Length | None: ...
    @begin_y.setter
    def begin_y(self, value: int) -> None: ...
    @property
    def end_x(self) -> _Length | None: ...
    @end_x.setter
    def end_x(self, value: int) -> None: ...
    @property
    def end_y(self) -> _Length | None: ...
    @end_y.setter
    def end_y(self, value: int) -> None: ...


@_final
class PlaceholderFormat:
    def __new__(cls, *, _private: _Never) -> PlaceholderFormat: ...
    @property
    def idx(self) -> int: ...
    @property
    def type(self) -> _PP_PLACEHOLDER: ...


@_final
class HeaderFooter:
    def __new__(cls, *, _private: _Never) -> HeaderFooter: ...
    @property
    def slide_number(self) -> bool: ...
    @slide_number.setter
    def slide_number(self, value: bool) -> None: ...
    @property
    def footer(self) -> str | None: ...
    @footer.setter
    def footer(self, value: str | None) -> None: ...
    @property
    def date(self) -> str | None: ...
    @date.setter
    def date(self, value: str | None) -> None: ...
    @property
    def date_format(self) -> str | None: ...
    @date_format.setter
    def date_format(self, value: str) -> None: ...


@_final
class SlideTransition:
    def __new__(cls, *, _private: _Never) -> SlideTransition: ...
    @property
    def type(self) -> str | None: ...
    @type.setter
    def type(self, value: _TransitionType | None) -> None: ...
    @property
    def direction(self) -> str | None: ...
    @direction.setter
    def direction(self, value: _TransitionDirection | None) -> None: ...
    @property
    def duration(self) -> float | None: ...
    @duration.setter
    def duration(self, value: float | None) -> None: ...
    @property
    def advance_on_click(self) -> bool: ...
    @advance_on_click.setter
    def advance_on_click(self, value: bool) -> None: ...
    @property
    def advance_after(self) -> float | None: ...
    @advance_after.setter
    def advance_after(self, value: float | None) -> None: ...
    def apply_to_all(self) -> None: ...


@_final
class SlideMaster:
    def __new__(cls, *, _private: _Never) -> SlideMaster: ...
    @property
    def theme(self) -> Theme: ...
    @property
    def shapes(self) -> ShapeCollection: ...
    @property
    def placeholders(self) -> PlaceholderCollection: ...
    @property
    def background(self) -> Background: ...
    @property
    def text_styles(self) -> MasterTextStyles: ...
    @property
    def slide_layouts(self) -> SlideLayoutCollection: ...
    def __eq__(self, other: object, /) -> bool: ...


@_final
class SlideMasterCollection:
    def __new__(cls, *, _private: _Never) -> SlideMasterCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> SlideMaster: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[SlideMaster]: ...
    def __iter__(self) -> _Iterator[SlideMaster]: ...


@_final
class Theme:
    def __new__(cls, *, _private: _Never) -> Theme: ...
    @property
    def name(self) -> str | None: ...
    @property
    def colors(self) -> ThemeColors: ...
    @property
    def fonts(self) -> ThemeFonts: ...


@_final
class ThemeColors:
    def __new__(cls, *, _private: _Never) -> ThemeColors: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str, /) -> bool: ...
    def __getitem__(self, key: str, /) -> _RGBColor | None: ...
    def __setitem__(self, key: str, value: _Color, /) -> None: ...
    def __iter__(self) -> _Iterator[str]: ...
    def keys(self) -> list[str]: ...
    def items(self) -> list[tuple[str, _RGBColor | None]]: ...


@_final
class ThemeFonts:
    def __new__(cls, *, _private: _Never) -> ThemeFonts: ...
    @property
    def major(self) -> ThemeFontSet: ...
    @property
    def minor(self) -> ThemeFontSet: ...


@_final
class ThemeFontSet:
    def __new__(cls, *, _private: _Never) -> ThemeFontSet: ...
    @property
    def latin(self) -> str: ...
    @latin.setter
    def latin(self, value: str) -> None: ...
    @property
    def east_asian(self) -> str: ...
    @east_asian.setter
    def east_asian(self, value: str) -> None: ...
    @property
    def complex_script(self) -> str: ...
    @complex_script.setter
    def complex_script(self, value: str) -> None: ...


@_final
class MasterTextStyles:
    def __new__(cls, *, _private: _Never) -> MasterTextStyles: ...
    @property
    def title(self) -> TextStyleList: ...
    @property
    def body(self) -> TextStyleList: ...
    @property
    def other(self) -> TextStyleList: ...


@_final
class TextStyleList:
    def __new__(cls, *, _private: _Never) -> TextStyleList: ...
    def __len__(self) -> int: ...
    def __getitem__(self, level: int, /) -> TextStyleLevel: ...


@_final
class TextStyleLevel:
    def __new__(cls, *, _private: _Never) -> TextStyleLevel: ...
    @property
    def font(self) -> Font: ...
    @property
    def bullet(self) -> str | bool | None: ...
    @bullet.setter
    def bullet(self, value: str | _Literal[False] | None) -> None: ...
    @property
    def bullet_color(self) -> _RGBColor | None: ...
    @bullet_color.setter
    def bullet_color(self, value: _Color | None) -> None: ...
    @property
    def left_indent(self) -> _Length | None: ...
    @left_indent.setter
    def left_indent(self, value: int | None) -> None: ...
    @property
    def first_line_indent(self) -> _Length | None: ...
    @first_line_indent.setter
    def first_line_indent(self, value: int | None) -> None: ...


@_final
class ShapeCollection:
    def __new__(cls, *, _private: _Never) -> ShapeCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Shape: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Shape]: ...
    def __iter__(self) -> _Iterator[Shape]: ...
    @property
    def title(self) -> Shape | None: ...
    @property
    def placeholders(self) -> PlaceholderCollection: ...
    def add_textbox(self, left: int, top: int, width: int, height: int) -> Shape: ...
    def add_shape(
        self, shape_type: _MSO_SHAPE | str, left: int, top: int, width: int, height: int
    ) -> Shape: ...
    def add_connector(
        self,
        connector_type: _MSO_CONNECTOR_TYPE,
        begin_x: int,
        begin_y: int,
        end_x: int,
        end_y: int,
    ) -> Shape: ...
    def add_group_shape(self, shapes: _Iterable[Shape] | None = None) -> Shape: ...
    def group(self, shapes: _Iterable[Shape]) -> Shape: ...
    def align(
        self,
        shapes: _Iterable[Shape],
        alignment: _Literal["left", "center", "right", "top", "middle", "bottom"],
        *,
        relative_to: _Literal["selection", "slide"] = "selection",
    ) -> None: ...
    def distribute(
        self,
        shapes: _Iterable[Shape],
        direction: _Literal["horizontal", "vertical"],
        *,
        relative_to: _Literal["selection", "slide"] = "selection",
    ) -> None: ...
    def add_table(
        self, rows: int, cols: int, left: int, top: int, width: int, height: int
    ) -> Shape: ...
    def add_picture(
        self,
        image_file: _ImageFile,
        left: int,
        top: int,
        width: int | None = None,
        height: int | None = None,
    ) -> Shape: ...
    def add_movie(
        self,
        movie_file: _ImageFile,
        left: int,
        top: int,
        width: int,
        height: int,
        poster_frame_image: _ImageFile | None = None,
        mime_type: str | None = None,
    ) -> Shape: ...
    def remove(self, shape: Shape) -> None: ...
    def move(self, from_: int, to: int) -> None: ...


@_final
class PlaceholderCollection:
    def __new__(cls, *, _private: _Never) -> PlaceholderCollection: ...
    def __getitem__(self, placeholder_idx: int, /) -> Shape: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> _Iterator[Shape]: ...


@_final
class Image:
    def __new__(cls, *, _private: _Never) -> Image: ...
    @property
    def blob(self) -> bytes: ...
    @property
    def content_type(self) -> str: ...
    @property
    def ext(self) -> str: ...


@_final
class AdjustmentCollection:
    def __new__(cls, *, _private: _Never) -> AdjustmentCollection: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int, /) -> float: ...
    def __setitem__(self, index: int, value: float, /) -> None: ...
    def __iter__(self) -> _Iterator[float]: ...


@_final
class FillFormat:
    def __new__(cls, *, _private: _Never) -> FillFormat: ...
    @property
    def type(self) -> _MSO_FILL_TYPE | None: ...
    def solid(self) -> None: ...
    def background(self) -> None: ...
    def gradient(self) -> None: ...
    def patterned(self) -> None: ...
    def picture(self, image_file: _ImageFile) -> None: ...
    @property
    def fore_color(self) -> ColorFormat: ...
    @property
    def back_color(self) -> ColorFormat: ...
    @property
    def pattern(self) -> _MSO_PATTERN_TYPE | None: ...
    @pattern.setter
    def pattern(self, value: _MSO_PATTERN_TYPE) -> None: ...
    @property
    def gradient_angle(self) -> float: ...
    @gradient_angle.setter
    def gradient_angle(self, value: float) -> None: ...
    @property
    def gradient_path(self) -> _Literal["circle", "rect", "shape"] | None: ...
    @gradient_path.setter
    def gradient_path(self, value: _Literal["circle", "rect", "shape"] | None) -> None: ...
    @property
    def gradient_stops(self) -> GradientStops: ...


@_final
class GradientStops:
    def __new__(cls, *, _private: _Never) -> GradientStops: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int, /) -> GradientStop: ...
    def __iter__(self) -> _Iterator[GradientStop]: ...
    def __delitem__(self, index: int, /) -> None: ...
    def append(self, position: float) -> GradientStop: ...


@_final
class GradientStop:
    def __new__(cls, *, _private: _Never) -> GradientStop: ...
    @property
    def color(self) -> ColorFormat: ...
    @property
    def position(self) -> float: ...
    @position.setter
    def position(self, value: float) -> None: ...


@_final
class LineFormat:
    def __new__(cls, *, _private: _Never) -> LineFormat: ...
    @property
    def color(self) -> ColorFormat: ...
    @property
    def fill(self) -> FillFormat: ...
    @property
    def width(self) -> _Length: ...
    @width.setter
    def width(self, value: int | None) -> None: ...
    @property
    def dash_style(self) -> _MSO_LINE_DASH_STYLE | None: ...
    @dash_style.setter
    def dash_style(self, value: _MSO_LINE_DASH_STYLE | None) -> None: ...
    @property
    def head_end(self) -> LineEndFormat: ...
    @property
    def tail_end(self) -> LineEndFormat: ...


@_final
class LineEndFormat:
    def __new__(cls, *, _private: _Never) -> LineEndFormat: ...
    @property
    def type(self) -> _MSO_ARROWHEAD_STYLE | None: ...
    @type.setter
    def type(self, value: _MSO_ARROWHEAD_STYLE | None) -> None: ...
    @property
    def width(self) -> _MSO_ARROWHEAD_WIDTH | None: ...
    @width.setter
    def width(self, value: _MSO_ARROWHEAD_WIDTH | None) -> None: ...
    @property
    def length(self) -> _MSO_ARROWHEAD_LENGTH | None: ...
    @length.setter
    def length(self, value: _MSO_ARROWHEAD_LENGTH | None) -> None: ...


@_final
class ColorFormat:
    def __new__(cls, *, _private: _Never) -> ColorFormat: ...
    @property
    def rgb(self) -> _RGBColor | None: ...
    @rgb.setter
    def rgb(self, value: _Color) -> None: ...
    @property
    def type(self) -> _MSO_COLOR_TYPE | None: ...
    @property
    def theme_color(self) -> _MSO_THEME_COLOR | None: ...
    @theme_color.setter
    def theme_color(self, value: _MSO_THEME_COLOR) -> None: ...
    @property
    def alpha(self) -> float | None: ...
    @alpha.setter
    def alpha(self, value: float) -> None: ...


_RectAlignment = _Literal["tl", "t", "tr", "l", "ctr", "r", "bl", "b", "br"]


@_final
class ShadowFormat:
    def __new__(cls, *, _private: _Never) -> ShadowFormat: ...
    @property
    def inherit(self) -> bool: ...
    @inherit.setter
    def inherit(self, value: bool) -> None: ...
    @property
    def visible(self) -> bool: ...
    @visible.setter
    def visible(self, value: bool) -> None: ...
    @property
    def color(self) -> ColorFormat: ...
    @property
    def alpha(self) -> float | None: ...
    @alpha.setter
    def alpha(self, value: float) -> None: ...
    @property
    def blur_radius(self) -> _Length | None: ...
    @blur_radius.setter
    def blur_radius(self, value: int) -> None: ...
    @property
    def distance(self) -> _Length | None: ...
    @distance.setter
    def distance(self, value: int) -> None: ...
    @property
    def direction(self) -> float | None: ...
    @direction.setter
    def direction(self, value: float) -> None: ...
    @property
    def align(self) -> _RectAlignment | None: ...
    @align.setter
    def align(self, value: _RectAlignment) -> None: ...
    @property
    def rotate_with_shape(self) -> bool | None: ...
    @rotate_with_shape.setter
    def rotate_with_shape(self, value: bool) -> None: ...


@_final
class TextFrame:
    def __new__(cls, *, _private: _Never) -> TextFrame: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def paragraphs(self) -> ParagraphCollection: ...
    def try_replace_text(
        self, placeholder: str, replacement: str, *, expect: int | None = None
    ) -> int: ...
    def add_paragraph(self) -> Paragraph: ...
    @property
    def autofit(self) -> str | None: ...
    @property
    def auto_size(self) -> _MSO_AUTO_SIZE | None: ...
    @auto_size.setter
    def auto_size(self, value: _MSO_AUTO_SIZE | None) -> None: ...
    @property
    def margin_left(self) -> _Length | None: ...
    @margin_left.setter
    def margin_left(self, value: int | None) -> None: ...
    @property
    def margin_right(self) -> _Length | None: ...
    @margin_right.setter
    def margin_right(self, value: int | None) -> None: ...
    @property
    def margin_top(self) -> _Length | None: ...
    @margin_top.setter
    def margin_top(self, value: int | None) -> None: ...
    @property
    def margin_bottom(self) -> _Length | None: ...
    @margin_bottom.setter
    def margin_bottom(self, value: int | None) -> None: ...
    @property
    def vertical_anchor(self) -> _MSO_ANCHOR | None: ...
    @vertical_anchor.setter
    def vertical_anchor(self, value: _MSO_ANCHOR | None) -> None: ...
    @property
    def word_wrap(self) -> bool | None: ...
    @word_wrap.setter
    def word_wrap(self, value: bool | None) -> None: ...


@_final
class Paragraph:
    def __new__(cls, *, _private: _Never) -> Paragraph: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def level(self) -> int: ...
    @level.setter
    def level(self, value: int) -> None: ...
    @property
    def font(self) -> Font: ...
    @property
    def runs(self) -> RunCollection: ...
    def add_run(self, text: str = "") -> Run: ...
    def add_field(self, field_type: str, text: str | None = None) -> None: ...
    @property
    def alignment(self) -> _PP_ALIGN | None: ...
    @alignment.setter
    def alignment(self, value: _PP_ALIGN | None) -> None: ...
    @property
    def line_spacing(self) -> float | _Length | None: ...
    @line_spacing.setter
    def line_spacing(self, value: float | _Length | None) -> None: ...
    @property
    def space_before(self) -> _Length | float | None: ...
    @space_before.setter
    def space_before(self, value: int | float | None) -> None: ...
    @property
    def space_after(self) -> _Length | float | None: ...
    @space_after.setter
    def space_after(self, value: int | float | None) -> None: ...
    @property
    def left_indent(self) -> _Length | None: ...
    @left_indent.setter
    def left_indent(self, value: int | None) -> None: ...
    @property
    def right_indent(self) -> _Length | None: ...
    @right_indent.setter
    def right_indent(self, value: int | None) -> None: ...
    @property
    def first_line_indent(self) -> _Length | None: ...
    @first_line_indent.setter
    def first_line_indent(self, value: int | None) -> None: ...
    @property
    def bullet(self) -> str | bool | None: ...
    @bullet.setter
    def bullet(self, value: str | bool | None) -> None: ...
    @property
    def auto_number(self) -> _AutoNumberScheme | None: ...
    @auto_number.setter
    def auto_number(self, value: _AutoNumberScheme | None) -> None: ...
    @property
    def auto_number_start(self) -> int | None: ...
    @auto_number_start.setter
    def auto_number_start(self, value: int | None) -> None: ...
    @property
    def bullet_color(self) -> _RGBColor | None: ...
    @bullet_color.setter
    def bullet_color(self, value: _Color | None) -> None: ...
    @property
    def bullet_size(self) -> float | None: ...
    @bullet_size.setter
    def bullet_size(self, value: float | None) -> None: ...
    @property
    def bullet_font(self) -> str | None: ...
    @bullet_font.setter
    def bullet_font(self, value: str | None) -> None: ...


@_final
class ParagraphCollection:
    def __new__(cls, *, _private: _Never) -> ParagraphCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Paragraph: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Paragraph]: ...
    def __iter__(self) -> _Iterator[Paragraph]: ...


@_final
class Run:
    def __new__(cls, *, _private: _Never) -> Run: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def font(self) -> Font: ...
    @property
    def hyperlink(self) -> Hyperlink: ...


@_final
class Hyperlink:
    def __new__(cls, *, _private: _Never) -> Hyperlink: ...
    @property
    def address(self) -> str | None: ...
    @address.setter
    def address(self, value: str | None) -> None: ...
    @property
    def target_slide(self) -> Slide | None: ...
    @target_slide.setter
    def target_slide(self, value: Slide | None) -> None: ...


@_final
class ShapeClickAction:
    def __new__(cls, *, _private: _Never) -> ShapeClickAction: ...
    @property
    def hyperlink(self) -> ShapeHyperlink: ...
    @property
    def target_slide(self) -> Slide | None: ...
    @target_slide.setter
    def target_slide(self, value: Slide | None) -> None: ...


@_final
class ShapeHyperlink:
    def __new__(cls, *, _private: _Never) -> ShapeHyperlink: ...
    @property
    def address(self) -> str | None: ...
    @address.setter
    def address(self, value: str | None) -> None: ...


@_final
class RunCollection:
    def __new__(cls, *, _private: _Never) -> RunCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Run: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Run]: ...
    def __iter__(self) -> _Iterator[Run]: ...


@_final
class Font:
    def __new__(cls, *, _private: _Never) -> Font: ...
    @property
    def name(self) -> str | None: ...
    @name.setter
    def name(self, value: str | None) -> None: ...
    @property
    def color(self) -> ColorFormat: ...
    @color.setter
    def color(self, value: _Color | None) -> None: ...
    @property
    def bold(self) -> bool | None: ...
    @bold.setter
    def bold(self, value: bool | None) -> None: ...
    @property
    def italic(self) -> bool | None: ...
    @italic.setter
    def italic(self, value: bool | None) -> None: ...
    @property
    def underline(self) -> bool | _MSO_UNDERLINE | None: ...
    @underline.setter
    def underline(self, value: bool | _MSO_UNDERLINE | None) -> None: ...
    @property
    def strike(self) -> bool | None: ...
    @strike.setter
    def strike(self, value: bool | None) -> None: ...
    @property
    def all_caps(self) -> bool | None: ...
    @all_caps.setter
    def all_caps(self, value: bool | None) -> None: ...
    @property
    def size(self) -> _Length | None: ...
    @size.setter
    def size(self, value: int | None) -> None: ...
    @property
    def baseline(self) -> float | None: ...
    @baseline.setter
    def baseline(self, value: float | None) -> None: ...
    @property
    def spacing(self) -> _Length | None: ...
    @spacing.setter
    def spacing(self, value: int | None) -> None: ...
    @property
    def language(self) -> str | None: ...
    @language.setter
    def language(self, value: str | None) -> None: ...
    @property
    def language_id(self) -> _MSO_LANGUAGE_ID: ...
    @language_id.setter
    def language_id(self, value: _MSO_LANGUAGE_ID | None) -> None: ...
    @property
    def east_asian_name(self) -> str | None: ...
    @east_asian_name.setter
    def east_asian_name(self, value: str | None) -> None: ...
    @property
    def complex_script_name(self) -> str | None: ...
    @complex_script_name.setter
    def complex_script_name(self, value: str | None) -> None: ...
    @property
    def highlight_color(self) -> _RGBColor | None: ...
    @highlight_color.setter
    def highlight_color(self, value: _Color | None) -> None: ...
    @property
    def small_caps(self) -> bool | None: ...
    @small_caps.setter
    def small_caps(self, value: bool | None) -> None: ...


@_final
class Table:
    def __new__(cls, *, _private: _Never) -> Table: ...
    @property
    def columns(self) -> ColumnCollection: ...
    @property
    def rows(self) -> RowCollection: ...
    def cell(self, row: int, col: int) -> Cell: ...
    @property
    def first_row(self) -> bool: ...
    @first_row.setter
    def first_row(self, value: bool) -> None: ...
    @property
    def last_row(self) -> bool: ...
    @last_row.setter
    def last_row(self, value: bool) -> None: ...
    @property
    def first_col(self) -> bool: ...
    @first_col.setter
    def first_col(self, value: bool) -> None: ...
    @property
    def last_col(self) -> bool: ...
    @last_col.setter
    def last_col(self, value: bool) -> None: ...
    @property
    def horz_banding(self) -> bool: ...
    @horz_banding.setter
    def horz_banding(self, value: bool) -> None: ...
    @property
    def vert_banding(self) -> bool: ...
    @vert_banding.setter
    def vert_banding(self, value: bool) -> None: ...
    @property
    def style_id(self) -> str | None: ...
    @style_id.setter
    def style_id(self, value: str | None) -> None: ...


@_final
class ColumnCollection:
    def __new__(cls, *, _private: _Never) -> ColumnCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Column: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Column]: ...
    def __iter__(self) -> _Iterator[Column]: ...
    def add_column(self, index: int | None = None) -> Column: ...
    def remove(self, column: Column) -> None: ...


@_final
class Column:
    def __new__(cls, *, _private: _Never) -> Column: ...
    @property
    def width(self) -> int: ...
    @width.setter
    def width(self, value: int) -> None: ...


@_final
class RowCollection:
    def __new__(cls, *, _private: _Never) -> RowCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Row: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Row]: ...
    def __iter__(self) -> _Iterator[Row]: ...
    def add_row(self, index: int | None = None) -> Row: ...
    def remove(self, row: Row) -> None: ...


@_final
class Row:
    def __new__(cls, *, _private: _Never) -> Row: ...
    @property
    def height(self) -> _Length: ...
    @height.setter
    def height(self, value: int) -> None: ...


@_final
class Cell:
    def __new__(cls, *, _private: _Never) -> Cell: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def text_frame(self) -> TextFrame: ...
    @property
    def vertical_anchor(self) -> _MSO_ANCHOR | None: ...
    @vertical_anchor.setter
    def vertical_anchor(self, value: _MSO_ANCHOR | None) -> None: ...
    def merge(self, other_cell: Cell) -> None: ...
    def split(self) -> None: ...
    @property
    def is_merge_origin(self) -> bool: ...
    @property
    def is_spanned(self) -> bool: ...
    @property
    def span_height(self) -> int: ...
    @property
    def span_width(self) -> int: ...
    @property
    def fill(self) -> FillFormat: ...
    @property
    def margin_left(self) -> _Length | None: ...
    @margin_left.setter
    def margin_left(self, value: int | None) -> None: ...
    @property
    def margin_right(self) -> _Length | None: ...
    @margin_right.setter
    def margin_right(self, value: int | None) -> None: ...
    @property
    def margin_top(self) -> _Length | None: ...
    @margin_top.setter
    def margin_top(self, value: int | None) -> None: ...
    @property
    def margin_bottom(self) -> _Length | None: ...
    @margin_bottom.setter
    def margin_bottom(self, value: int | None) -> None: ...
    @property
    def border_left(self) -> LineFormat: ...
    @property
    def border_right(self) -> LineFormat: ...
    @property
    def border_top(self) -> LineFormat: ...
    @property
    def border_bottom(self) -> LineFormat: ...
